### ISSUE TITLE
Update github action to point to renamed nipoppy forks

### ISSUE THREAD

**Issue by nikhil153** [neurodatascience/nipoppy#124]
@michellewang is [this](https://github.com/neurodatascience/nipoppy/blob/main/.github/workflows/update_dataset_repos.yml#L13-L17) this only place we need to update?

**Comment by michellewang** [comment]
@nikhil153 yes, I will make a PR right now. Do we still want to include https://github.com/neurodatascience/nipoppy_nimhans or was that just for the demo/walkthrough the other day?

**Comment by nikhil153** [comment]
Yes, lets add both of the following (recently renamed for clarity) 
- https://github.com/neurodatascience/nipoppy-nimhans_YLO (renamed from `nipoppy_nimhans`) 
- https://github.com/neurodatascience/nipoppy-nimhans_retro (renamed from `nipoppy-nimhans_serb`)
