### ISSUE TITLE
Add more files (or file patterns) for Codespell to ignore

### ISSUE THREAD

**Issue by michellewang** [neurodatascience/nipoppy#151]
- [MRIQC HTML files](https://github.com/neurodatascience/nipoppy-qpn/actions/runs/5953804894/job/16148916737)
- [ppmi_imaging_descriptions.json](https://github.com/neurodatascience/nipoppy-ppmi/commit/4333b43783444dffcd04ad5fbc3cc246b33937d1#annotation_13597869649) (PPMI-specific)

The other failures are actual spelling errors

**Comment by michellewang** [comment]
I don't think there is a straightforward way to configure Codespell differently for each repo (using the same workflow file) so it would all need to be done in the template repo

**Comment by Remi-Gau** [comment]
yeah I don't think there is non headache inducing way to do this so centralizing those exceptions in the parent repo makes sense for now
