### ISSUE TITLE
Use `participant_id` as `dicom_dir` by default instead of skipping check in `check_dicom_status.py`

### ISSUE THREAD

**Issue by michellewang** [neurodatascience/nipoppy#152]
> Maybe it can be another PR, but should we also change the default expectation of `dicom_dir` name - which currently depends on this [import](https://github.com/neurodatascience/nipoppy/blob/b0285b70f68881015af058362a5f32231c1bb829/nipoppy/workflow/dicom_org/check_dicom_status.py#L117)?

_Originally posted by @nikhil153 in https://github.com/neurodatascience/nipoppy/pull/145#pullrequestreview-1592135183_

**Comment by nikhil153** [comment]
I think it should be stripped participant_id (white-space / special chars)

**Comment by michellewang** [comment]
So using [`participant_id_to_dicom_id`](https://github.com/neurodatascience/nipoppy/blob/main/nipoppy/workflow/utils.py#L41-L45)?

**Comment by nikhil153** [comment]
that works!
