### ISSUE TITLE
Handle `session_id` in `participant_id_to_dicom_dir.py` helper function used in `check_dicom_status.py`

### ISSUE THREAD

**Issue by nikhil153** [neurodatascience/nipoppy#164]
@michellewang, 
Its unclear to me how the mapping function [participant_id_to_dicom_dir](https://github.com/neurodatascience/nipoppy/blob/main/nipoppy/workflow/dicom_org/check_dicom_status.py#L129-L131) is supposed to handle multiple sessions from the same participant. 

My guess is that either we have to pass the `session_id` in this call or change the lambda function approach.

**Comment by michellewang** [comment]
I hadn't thought about that. I think it would make sense to add `session_id` to the function call. Are there any other variables that we would need here (apart from `participant_id`, `session_id`, and `global_config`)?
