### ISSUE TITLE
Bring back `INCOMPLETE` status in derivatives bagel

### ISSUE THREAD

**Issue by michellewang** [neurodatascience/nipoppy#176]
So we will have 4 statuses, with the logic being:
* `UNAVAILABLE`: The subject **does not have** the required MRI datatype for this session (based on the manifest)
* If the right MRI datatype(s) are theoretically available for this subject-session pair:
  * `INCOMPLETE`: The expected parent directory for the derivatives **does not exist** -> the pipeline hasn't been run yet
    * The directory to check must be **specific to both the subject AND the session**. For example for fMRIPrep it should be `.../sub-<SUBJECT>/ses-<SESSION>`, and for Freesurfer it should be `.../ses-<SESSION>/sub-<SUBJECT>`
  * If the expected parent directory for the derivatives exists:
    * `SUCCESS`: **all files** specified in the tracker exist
    * `FAIL`: at least one file specified in the tracker **does not exist**

@alyssadai @nikhil153 does that look okay?

**Comment by alyssadai** [comment]
Hey @michellewang, @nikhil153, this looks reasonable to me. If you have a prototype derivatives bagel that includes `INCOMPLETE` status values, you should already be able to test it in the current version of the dashboard (it doesn't do any validation of the column values in the bagel yet, so the `range` of values specified in the schema is basically a recommendation for now). The in-table filtering and plotting at least should still work.

I believe the main changes in the dashboard code will be to
1. add the `INCOMPLETE` status back to the pipeline status legend
2. add it back as a dropdown option under the "Advanced Filtering Options" part of the dashboard (the available pipeline status options are currently hardcoded to discourage too many arbitrary values/stay aligned with the schema-defined `range`s, but this can be changed if desired)
3. add it back to the schema for an imaging bagel

(1) and (2) are highlighted in the screenshot below
<img width="950" alt="ui_overview_plots_annot" src="https://github.com/neurodatascience/nipoppy/assets/65699389/9d098bc2-acfc-4ab6-8795-4f635790fd8d">

If that sounds good, I'll create a corresponding issue for this update in the dashboard 🙂

**Comment by nikhil153** [comment]
Overall looks good. One question would be: do we use `datatype` info from the manifest to decide `INCOMPLETE` status. Since availability of T1w / dti / func could be different for each session.

**Comment by michellewang** [comment]
@alyssadai that sounds good!

@nikhil153 my thought was that if they didn't have the expected `datatype` for that subject/session then the status would be `UNAVAILABLE` (manifest has datatype for subject and session so that works). `INCOMPLETE` would be if *in theory* they should have results available but we don't find any (because they weren't run or BIDS conversion was not successful). And `FAIL` is if we *know* processing was started but the expected result files are not found

**Comment by nikhil153** [comment]
@michellewang - yes I think we are saying the same thing. 
> if they didn't have the expected `datatype` for that subject/session then the status would be UNAVAILABLE

Yup

> INCOMPLETE would be if in theory they should have results available but we don't find any

This would be based on the fact that there is an expected `datatype` entry for that `participant_id` x `session` combination, but no session-specific output data-dir on disk, correct?

**Comment by michellewang** [comment]
> This would be based on the fact that there is an expected datatype entry for that participant_id x session combination, but no session-specific output data-dir on disk, correct?

Yes exactly!
