### ISSUE TITLE
JSON schemas not showing in the docs

### ISSUE THREAD

**Issue by michellewang** [neurodatascience/nipoppy#217]
Should be something like:

<img width="771" alt="Screenshot 2024-05-07 at 10 01 07 PM" src="https://github.com/neurodatascience/nipoppy/assets/29051929/de3e949b-4753-4b24-acf5-54ab8db9d8b0">

Instead we have:

<img width="765" alt="Screenshot 2024-05-07 at 10 01 33 PM" src="https://github.com/neurodatascience/nipoppy/assets/29051929/947f1b75-0d7b-4f84-825e-20db2e3324a7">

Turns out Read the Docs does not use the Makefile (at least not by default), see [here](https://stackoverflow.com/questions/69494093/building-documentation-in-rtd-using-a-makefile). Maybe a solution would be to use [`build.commands`](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-commands) to override the default behaviour (i.e. run the `pydantic_to_jsonschema.py` script then run `python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html`), though that feature is in beta.

It would be good to have the doc building process fail on errors if possible.

**Comment by Remi-Gau** [comment]
Have a look at the bids spec RTD config.

I think it may answer both points.

https://github.com/bids-standard/bids-specification/blob/master/readthedocs.yml

**Comment by Remi-Gau** [comment]
closed by #218
