### ISSUE TITLE
Improve performance of the CLI

### ISSUE THREAD

**Issue by mathdugre** [neurodatascience/nipoppy#279]
The majority of the execution time for the CLI is spent importing packages, with most of the packages not being used by the CLI itself (see image  below). 

<img width="1142" alt="Screenshot 2024-07-12 at 15 49 24" src="https://github.com/user-attachments/assets/77a3fff6-e7e1-4448-ac1f-94a6ec43866b">

Generated using `python -X importtime nipoppy_cli/nipoppy/cli/run.py 2> cli.log` then `tuna cli.log`

**Comment by Remi-Gau** [comment]
@mathdugre 
can you explain how you generated this graph?
Future me may need this.

**Comment by mathdugre** [comment]
I edited the original comment to include the commands used to generate the flamegraph.

**Comment by Remi-Gau** [comment]
Merci!!!
